// react-spa/src/components/Home.jsx
// src/components/Home.jsx

import { useMsal } from "@azure/msal-react";
import { useState, useEffect } from "react";
import { loginRequest } from "../authConfig";
import "./home.css";

export default function Home() {
  const { instance, accounts } = useMsal();
  const account = accounts[0];

  const [tokenType, setTokenType] = useState("id");
  const [accessToken, setAccessToken] = useState(null);
  const [copied, setCopied] = useState(false);

  // Acquire access token on load
  useEffect(() => {
    if (!account) return;

    async function fetchAccessToken() {
      try {
        const result = await instance.acquireTokenSilent({
          ...loginRequest,
          account: account
        });
        setAccessToken(result.accessToken);
      } catch (err) {
        console.error("Failed to acquire access token:", err);
      }
    }

    fetchAccessToken();
  }, [instance, account]);

  // Rolling inactivity logout timer
  useEffect(() => {
    if (!account) return;

    const minutes = parseInt(process.env.REACT_APP_LOGOUT_MINUTES || "60", 10);
    const timeoutMs = minutes * 60 * 1000;

    let timer;

    const resetTimer = () => {
      clearTimeout(timer);
      timer = setTimeout(() => {
        instance.logoutRedirect({
          account: instance.getActiveAccount(),
          postLogoutRedirectUri: "/logout",
          logoutHint: instance.getActiveAccount()?.username
        });
      }, timeoutMs);
    };

    resetTimer();

    const activityEvents = ["mousemove", "mousedown", "keydown", "touchstart", "scroll"];
    activityEvents.forEach((event) => window.addEventListener(event, resetTimer));

    return () => {
      clearTimeout(timer);
      activityEvents.forEach((event) => window.removeEventListener(event, resetTimer));
    };
  }, [account, instance]);

  // Extract claims
  const idClaims = account?.idTokenClaims || {};
  const accessClaims = accessToken ? parseJwt(accessToken) : {};
  const claims = tokenType === "id" ? idClaims : accessClaims;

  // Current token string
  const currentToken =
    tokenType === "id"
      ? account?.idToken
      : accessToken || "";

  // Copy handler
  const handleCopy = () => {
    navigator.clipboard.writeText(currentToken);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div className="home-container">

      {/* HEADER */}
      <header className="app-header">
        <h1 className="header-title">React SPA</h1>

        <button
          className="logout-button"
          onClick={() =>
            instance.logoutRedirect({
              account: instance.getActiveAccount(),
              postLogoutRedirectUri: "/logout",
              logoutHint: instance.getActiveAccount()?.username
            })
          }
        >
          Logout
        </button>
      </header>

      {/* MAIN CONTENT */}
      <main className="main-content">
        <p>You are authenticated via Entra External ID.</p>

        <div className="token-selector">
          <label>Select token:</label>
          <select
            value={tokenType}
            onChange={(e) => setTokenType(e.target.value)}
          >
            <option value="id">ID Token</option>
            <option value="access">Access Token</option>
          </select>
        </div>

        {/* NEW: Token display + copy button */}
        <div className="token-display">
          <h2>Current {tokenType === "id" ? "ID Token" : "Access Token"}:</h2>

          <div className="token-box">
            <textarea
              readOnly
              value={currentToken}
              className="token-textarea"
            />

            <button className="copy-button" onClick={handleCopy}>
              {copied ? "Copied!" : "Copy"}
            </button>
          </div>
        </div>

        <h2>JWT Claims ({tokenType === "id" ? "ID Token" : "Access Token"})</h2>

        <div className="claims-container">
          {Object.entries(claims).map(([key, value]) => (
            <div key={key} className="claim-row">
              <span className="claim-name">{key}</span>
              <span className="claim-value">
                {typeof value === "object" ? JSON.stringify(value) : String(value)}
              </span>
            </div>
          ))}
        </div>
      </main>

      {/* FOOTER */}
      <footer className="app-footer">
        © 2026 JG Labs Inc — All Rights Reserved
      </footer>

    </div>
  );
}

// Helper to decode JWT access token
function parseJwt(token) {
  try {
    const base64 = token.split(".")[1].replace(/-/g, "+").replace(/_/g, "/");
    return JSON.parse(window.atob(base64));
  } catch {
    return {};
  }
}

// vue-spa/src/views/Home.vue
<template>
  <div class="home-container">
    <header class="app-header">
      <h1 class="header-title">Vue SPA - Task Viewer</h1>
      <button class="logout-button" @click="logoutUser">Logout</button>
    </header>

    <main class="main-content">
      <h2>Your Tasks</h2>

      <!-- Error Banner -->
      <div v-if="errorMessage" class="error-banner">
        <span>{{ errorMessage }}</span>
        <button class="retry-button" @click="loadTasks">Retry</button>
      </div>

      <!-- Loading Spinner -->
      <div v-if="isLoading" class="spinner-container">
        <div class="spinner"></div>
        <p>Loading tasks...</p>
      </div>

      <!-- Refresh Button -->
      <button @click="loadTasks" class="copy-button" :disabled="isLoading">
        Refresh Tasks
      </button>

      <!-- Task List -->
      <div class="claims-container" style="margin-top: 20px" v-if="!isLoading && !errorMessage">
        <div v-for="task in tasks" :key="task.id" class="claim-row">
          <span class="claim-name">{{ task.title }}</span>
          <span class="claim-value">{{ task.status }}</span>
        </div>
      </div>
    </main>

    <footer class="app-footer">
      © 2026 JG Labs Inc — All Rights Reserved
    </footer>
  </div>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount } from "vue";
import { useMsal } from "../composables/useMsal";
import { useRouter } from "vue-router";

const tasks = ref([]);
const isLoading = ref(false);
const errorMessage = ref("");

const { acquireApiToken } = useMsal();
const router = useRouter();

const API_BASE = import.meta.env.VITE_API_BASE_URL;

// ------------------------------
// Rolling inactivity logout
// ------------------------------
let inactivityTimer = null;

function startInactivityTimer() {
  const minutes = parseInt(import.meta.env.VITE_LOGOUT_MINUTES || "60", 10);
  const timeoutMs = minutes * 60 * 1000;

  clearTimeout(inactivityTimer);

  inactivityTimer = setTimeout(() => {
    logoutUser();
  }, timeoutMs);
}

function resetInactivityTimer() {
  startInactivityTimer();
}

async function logoutUser() {
  const { msalInstance } = await import("../msalInstance");

  const account =
    msalInstance.getActiveAccount() || msalInstance.getAllAccounts()[0];

  await msalInstance.logoutRedirect({
    account,
    postLogoutRedirectUri: "/logout"
  });
}

// ------------------------------
// Load tasks
// ------------------------------
async function loadTasks() {
  isLoading.value = true;
  errorMessage.value = "";

  try {
    const token = await acquireApiToken();
    if (!token) {
      throw new Error("Unable to acquire access token.");
    }

    const response = await fetch(`${API_BASE}/tasks`, {
      headers: {
        Authorization: `Bearer ${token}`
      }
    });

    if (!response.ok) {
      throw new Error(`API returned status ${response.status}`);
    }

    const data = await response.json();
    tasks.value = data.tasks || data;
  } catch (err) {
    errorMessage.value = "Failed to load tasks. Please try again.";
    console.error("Task load error:", err);
  } finally {
    isLoading.value = false;
  }
}

// ------------------------------
// Lifecycle
// ------------------------------
onMounted(() => {
  loadTasks();
  startInactivityTimer();

  const events = ["mousemove", "mousedown", "keydown", "touchstart", "scroll"];
  events.forEach((evt) =>
    window.addEventListener(evt, resetInactivityTimer)
  );
});

onBeforeUnmount(() => {
  clearTimeout(inactivityTimer);

  const events = ["mousemove", "mousedown", "keydown", "touchstart", "scroll"];
  events.forEach((evt) =>
    window.removeEventListener(evt, resetInactivityTimer)
  );
});
</script>

<style scoped src="../assets/home.css"></style>

<style scoped>
.error-banner {
  background-color: #ffdddd;
  color: #a30000;
  border: 1px solid #ffb3b3;
  padding: 12px 16px;
  border-radius: 6px;
  margin-bottom: 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.retry-button {
  background-color: #a30000;
  color: white;
  border: none;
  padding: 6px 12px;
  border-radius: 4px;
  cursor: pointer;
}

.retry-button:hover {
  background-color: #7a0000;
}

.spinner-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 20px 0;
}

.spinner {
  border: 4px solid #e0e0e0;
  border-top: 4px solid #0078d4;
  border-radius: 50%;
  width: 36px;
  height: 36px;
  animation: spin 0.8s linear infinite;
  margin-bottom: 10px;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>
